/*
 * Copyright (c) 2026 ghostflyby
 * SPDX-FileCopyrightText: 2026 ghostflyby
 * SPDX-License-Identifier: LGPL-3.0-or-later
 */

package dev.ghostflyby.mcp.filecontent.tools

import com.intellij.openapi.application.backgroundWriteAction
import com.intellij.openapi.application.readAction
import com.intellij.openapi.components.service
import com.intellij.openapi.diff.impl.patch.PatchHunk
import com.intellij.openapi.diff.impl.patch.PatchReader
import com.intellij.openapi.diff.impl.patch.TextFilePatch
import com.intellij.openapi.diff.impl.patch.apply.GenericPatchApplier
import com.intellij.openapi.editor.Document
import com.intellij.openapi.fileEditor.FileDocumentManager
import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.VfsUtil
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.openapi.vfs.VirtualFileManager
import com.intellij.psi.PsiDocumentManager
import dev.ghostflyby.mcp.common.WorkspaceResourceException
import dev.ghostflyby.mcp.route.McpCallContext
import dev.ghostflyby.mcp.route.project
import kotlinx.schema.Description
import kotlinx.schema.Schema
import java.nio.file.InvalidPathException
import java.nio.file.Path

internal class FileContentWriteTools {
    @Schema
    @Suppress("unused")
    internal suspend fun McpCallContext<*>.documentApplyGitPatch(
        @Description("Git unified diff patch (generated by git diff)")
        patch: String,
    ): DocumentPatchResult {
        val project = call.project()
        val patches: List<TextFilePatch> = PatchReader(patch).readTextPatches()
        if (patches.isEmpty()) throw WorkspaceResourceException("No file patches found")
        val succeeded = ArrayList<PatchFileSuccess>(patches.size)
        val failed = mutableListOf<PatchFileError>()
        for (textPatch in patches) {
            val path = textPatch.afterName ?: textPatch.beforeName
            ?: throw WorkspaceResourceException("Patch has no target file")
            try {
                val target = resolveProjectPatchPath(project, path)
                succeeded += when {
                    textPatch.isNewFile -> createPatchedFile(project, target, textPatch.getSingleHunkPatchText())
                    textPatch.isDeletedFile -> deletePatchedFile(target, textPatch.hunks)
                    else -> applyPatchToFile(project, target, textPatch.hunks)
                }
            } catch (e: Exception) {
                failed += PatchFileError(path, e.message ?: "Unknown error")
            }
        }
        return DocumentPatchResult(succeeded, failed)
    }

    @Schema
    @Suppress("unused")
    internal suspend fun McpCallContext<*>.documentApplyCodexPatch(
        @Description("Codex/OpenAI apply_patch block (*** Begin Patch / *** End Patch wrapper)")
        patch: String,
    ): DocumentPatchResult {
        val project = call.project()
        val fileSections = splitCodexByFile(patch)
        if (fileSections.isEmpty()) throw WorkspaceResourceException("No file patches found")
        val succeeded = ArrayList<PatchFileSuccess>(fileSections.size)
        val failed = mutableListOf<PatchFileError>()
        for (section in fileSections) {
            try {
                val target = resolveProjectPatchPath(project, section.filePath)
                succeeded += when (section.operation) {
                    CodexFileOperation.ADD -> createPatchedFile(project, target, parseCodexAddContent(section.rawLines))
                    CodexFileOperation.DELETE -> deletePatchedFile(target, emptyList())
                    CodexFileOperation.UPDATE -> {
                        val (_, document) = resolveTextDocumentForTool(target)
                        val hunks = parseCodexRawHunks(section.rawLines, document.immutableCharSequence)
                            ?: throw WorkspaceResourceException("No hunks in: ${section.filePath}")
                        val applied = GenericPatchApplier.apply(document.immutableCharSequence, hunks)
                            ?: throw WorkspaceResourceException("Patch does not apply for: ${section.filePath}")
                        ensureToolWritable(target, document)
                        backgroundWriteAction {
                            document.setText(applied.patchedText)
                            commitDocument(project, document)
                        }
                        PatchFileSuccess(target.relativePath, "update", snapshotToolWriteResult(document))
                    }
                }
            } catch (e: Exception) {
                failed += PatchFileError(section.filePath, e.message ?: "Unknown error")
            }
        }
        return DocumentPatchResult(succeeded, failed)
    }

    private suspend fun applyPatchToFile(
        project: Project,
        target: ProjectPatchPath,
        hunks: List<PatchHunk>,
    ): PatchFileSuccess {
        val (_, document) = resolveTextDocumentForTool(target)
        ensureToolWritable(target, document)
        val applied = GenericPatchApplier.apply(document.immutableCharSequence, hunks)
            ?: throw WorkspaceResourceException("Patch does not apply")
        backgroundWriteAction {
            document.setText(applied.patchedText)
            commitDocument(project, document)
        }
        return PatchFileSuccess(target.relativePath, "update", snapshotToolWriteResult(document))
    }
}

private data class ProjectPatchPath(
    val relativePath: String,
    val nioPath: Path,
    val url: String,
)

private fun resolveProjectPatchPath(
    project: Project,
    path: String,
): ProjectPatchPath {
    val basePath = project.basePath
        ?: throw WorkspaceResourceException("Project has no base path; cannot resolve: $path")
    val base = try {
        Path.of(basePath).toAbsolutePath().normalize()
    } catch (e: InvalidPathException) {
        throw WorkspaceResourceException("Project base path is invalid: ${e.input}")
    }
    val rawPath = filePathFromPatchTarget(path)
    val target = try {
        val parsed = Path.of(rawPath)
        if (parsed.isAbsolute) parsed.normalize() else base.resolve(parsed).normalize()
    } catch (e: InvalidPathException) {
        throw WorkspaceResourceException("Patch target path is invalid: ${e.input}")
    }
    if (!target.startsWith(base)) {
        throw WorkspaceResourceException("Patch target is outside the project directory: $path")
    }
    val relativePath = base.relativize(target).toString().replace('\\', '/')
    return ProjectPatchPath(relativePath = relativePath, nioPath = target, url = "file://$target")
}

private fun filePathFromPatchTarget(path: String): String {
    if (!path.contains("://")) return path
    if (!path.startsWith("file://")) {
        throw WorkspaceResourceException("Only project-local file:// patch targets are supported: $path")
    }
    return path.removePrefix("file://")
}

private suspend fun createPatchedFile(project: Project, target: ProjectPatchPath, text: String): PatchFileSuccess {
    val document = backgroundWriteAction {
        if (service<VirtualFileManager>().findFileByUrl(target.url) != null) {
            throw WorkspaceResourceException("File already exists: ${target.relativePath}")
        }
        val parentPath = target.nioPath.parent
            ?: throw WorkspaceResourceException("Patch target has no parent directory: ${target.relativePath}")
        val parent = VfsUtil.createDirectories(parentPath.toString())
        val file = parent.createChildData(FileContentWriteTools::class.java, target.nioPath.fileName.toString())
        val document = FileDocumentManager.getInstance().getDocument(file)
            ?: throw WorkspaceResourceException("Created file has no text document: ${target.relativePath}")
        document.setText(text)
        commitDocument(project, document)
        document
    }
    return PatchFileSuccess(target.relativePath, "add", snapshotToolWriteResult(document))
}

private suspend fun deletePatchedFile(
    target: ProjectPatchPath,
    hunks: List<PatchHunk>,
): PatchFileSuccess {
    val (file, document) = resolveTextDocumentForTool(target)
    ensureFileWritable(file, target)
    if (hunks.isNotEmpty()) {
        GenericPatchApplier.apply(document.immutableCharSequence, hunks)
            ?: throw WorkspaceResourceException("Patch does not apply")
    }
    backgroundWriteAction {
        file.delete(FileContentWriteTools::class.java)
    }
    return PatchFileSuccess(target.relativePath, "delete")
}

private suspend fun resolveTextDocumentForTool(target: ProjectPatchPath): Pair<VirtualFile, Document> = readAction {
    val vfsManager = service<VirtualFileManager>()
    val file = vfsManager.findFileByUrl(target.url)
        ?: throw WorkspaceResourceException("File not found: ${target.relativePath}")
    if (file.isDirectory) throw WorkspaceResourceException("Patch target is a directory, not a file: ${target.relativePath}")
    val document = FileDocumentManager.getInstance().getDocument(file)
        ?: throw WorkspaceResourceException("File at '${target.relativePath}' is binary or has no text document")
    file to document
}

private suspend fun ensureToolWritable(target: ProjectPatchPath, document: Document) {
    val writable = readAction { document.isWritable }
    if (!writable) throw WorkspaceResourceException("Document is not writable: ${target.relativePath}")
}

private suspend fun ensureFileWritable(file: VirtualFile, target: ProjectPatchPath) {
    val writable = readAction { file.isWritable }
    if (!writable) throw WorkspaceResourceException("File is not writable: ${target.relativePath}")
}

private suspend fun snapshotToolWriteResult(document: Document): DocumentSdkWriteResult {
    val (len, lines, stamp) = readAction { Triple(document.textLength, document.lineCount, document.modificationStamp) }
    return DocumentSdkWriteResult(textLength = len, lineCount = lines, modificationStamp = stamp)
}

private fun commitDocument(project: Project, document: Document) {
    val mgr = PsiDocumentManager.getInstance(project)
    mgr.doPostponedOperationsAndUnblockDocument(document)
    mgr.commitDocument(document)
}
