# GitHub Actions Workflow created for handling the release process based on the draft release prepared with the Build workflow.
# Running the publishPlugin task requires all the following secrets to be provided: PUBLISH_TOKEN, PRIVATE_KEY, PRIVATE_KEY_PASSWORD, CERTIFICATE_CHAIN.
# See https://plugins.jetbrains.com/docs/intellij/plugin-signing.html for more information.

name: Release
on:
  release:
    types: [ published ]

defaults:
  run:
    shell: pwsh

jobs:

  # Prepare and publish the plugin to JetBrains Marketplace repository
  release:
    name: Publish Plugin
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      # Free GitHub Actions Environment Disk Space
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          large-packages: false

      # Check out the current repository
      - name: Fetch Sources
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.tag_name }}

      # Set up the Java environment for the next steps
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: jetbrains
          java-version: 21
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Setup Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: true

      # Resolve module from tag (format: plugins/<module>-vX.Y.Z)
      - name: Resolve module
        id: mod
        run: |
          $tag = ""
          $modPath = $tag -replace "-v.*$", ""
          $gradlePath = ":$($modPath.Replace("/", ":") )"
          "module_path=$modPath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          "gradle_path=$gradlePath" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      # Set environment variables
      - name: Export Properties
        id: properties
        env:
          RELEASE_BODY: ${{ github.event.release.body }}
        run: |
          $changelog = $env:RELEASE_BODY -replace "(?m)^\s*$", ""
          $changelog = $changelog.TrimStart()

          "changelog<<EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          $changelog | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          "EOF" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

      # Update the Unreleased section with the current release note
      - name: Patch Changelog
        if: ${{ github.event.release.body != '' }}
        env:
          CHANGELOG: ${{ github.event.release.body }}
        run: |
          $gradlew = if ($IsWindows)
          {
              ".\gradlew.bat"
          }
          else
          {
              "./gradlew"
          }
          $releaseNote = New-TemporaryFile
          Set-Content -Path $releaseNote -Value $env:CHANGELOG -Encoding utf8

          & $gradlew --configuration-cache:patchChangelog --release-note-file="$releaseNote"
          Remove-Item $releaseNote

      # Publish the plugin to JetBrains Marketplace
      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          CERTIFICATE_CHAIN: ${{ secrets.CERTIFICATE_CHAIN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PRIVATE_KEY_PASSWORD: ${{ secrets.PRIVATE_KEY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: |
          $gradlew = if ($IsWindows)
          {
              ".\gradlew.bat"
          }
          else
          {
              "./gradlew"
          }
          & $gradlew --configuration-cache:publishPlugin

      # Create a pull request
      - name: Create Pull Request
        if: ${{ github.event.release.body != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $version = ""
          $branch = "changelog-update-$version"
          $label = "release changelog"

          git config user.email "action@github.com"
          git config user.name "GitHub Action"

          git checkout -b $branch
          git commit -am "chore: Changelog update - $version [skip ci]"
          git push --set-upstream origin $branch
          
          gh label create "$label" `
            --description "Pull requests with release changelog update" `
            --force

          $prUrl = gh pr create `
            --title "chore: Changelog update - $version [skip ci]" `
            --body "Current pull request contains patched CHANGELOG.md file for the $version version." `
            --label "$label" `
            --head "$branch"
          
          gh pr merge "$prUrl" --squash --auto
